"use strict";

function createApiHandlers({agentAuthService, environmentKeysService, goalsService, openAiCodexAuthService, piModelsService, piPackagesService, qaFaultHarnessService, workspaceAgentAssetsService, workspaceService, githubService, googleWorkspaceService = {}, operations}) {
  const goals = goalsService || {
    listGoals: async () => ({}),
    createGoal: async () => ({}),
    getGoal: async () => ({}),
    getGoalRuntime: async () => ({}),
    updateGoal: async () => ({}),
    actionGoal: async () => ({}),
    answerGoalQuestion: async () => ({}),
    listGoalEvents: async () => ({}),
    getGoalOperation: async () => ({}),
  };
  return Object.freeze({
    ...operations,
    getPiAuth: agentAuthService.getPiAuth,
    savePiAuthProvider: agentAuthService.savePiAuthProvider,
    deletePiAuthProvider: agentAuthService.deletePiAuthProvider,
    deletePiAuthEntry: agentAuthService.deletePiAuthEntry,
    listGenericEnvironmentKeys: environmentKeysService.listGenericEnvironmentKeys,
    createGenericEnvironmentKey: environmentKeysService.createGenericEnvironmentKey,
    updateGenericEnvironmentKey: environmentKeysService.updateGenericEnvironmentKey,
    deleteGenericEnvironmentKey: environmentKeysService.deleteGenericEnvironmentKey,
    startOpenAiCodexDeviceCode: openAiCodexAuthService.startOpenAiCodexDeviceCode,
    completeOpenAiCodexDeviceCode: openAiCodexAuthService.completeOpenAiCodexDeviceCode,
    saveSessionPiAuthSelection: agentAuthService.saveSessionPiAuthSelection,
    listPiModels: piModelsService.listPiModels,
    readPiModelsFile: piModelsService.readPiModelsFile,
    savePiModelScope: piModelsService.savePiModelScope,
    savePiModelsFile: piModelsService.savePiModelsFile,
    listPiPackages: piPackagesService.listPiPackages,
    installPiPackage: piPackagesService.installPiPackage,
    removePiPackage: piPackagesService.removePiPackage,
    updatePiPackage: piPackagesService.updatePiPackage,
    getSessionQaFaults: qaFaultHarnessService?.getStatus || (async () => { throw new Error("QA fault harness service is unavailable"); }),
    armSessionQaFault: qaFaultHarnessService?.arm || (async () => { throw new Error("QA fault harness service is unavailable"); }),
    listGoals: goals.listGoals,
    createGoal: goals.createGoal,
    getGoal: goals.getGoal,
    getGoalRuntime: goals.getGoalRuntime,
    updateGoal: goals.updateGoal,
    actionGoal: goals.actionGoal,
    answerGoalQuestion: goals.answerGoalQuestion,
    listGoalEvents: goals.listGoalEvents,
    getGoalOperation: goals.getGoalOperation,
    listWorkspaceSkills: workspaceAgentAssetsService.listWorkspaceSkills,
    saveWorkspaceSkill: workspaceAgentAssetsService.saveWorkspaceSkill,
    deleteWorkspaceSkill: workspaceAgentAssetsService.deleteWorkspaceSkill,
    listPiSkills: workspaceAgentAssetsService.listPiSkills,
    savePiSkill: workspaceAgentAssetsService.savePiSkill,
    deletePiSkill: workspaceAgentAssetsService.deletePiSkill,
    listWorkspaceSubagents: workspaceAgentAssetsService.listWorkspaceSubagents,
    saveWorkspaceSubagent: workspaceAgentAssetsService.saveWorkspaceSubagent,
    deleteWorkspaceSubagent: workspaceAgentAssetsService.deleteWorkspaceSubagent,
    listWorkspaces: workspaceService.listWorkspaces,
    createWorkspace: workspaceService.createWorkspace,
    renameWorkspace: workspaceService.renameWorkspace,
    deleteWorkspace: workspaceService.deleteWorkspace,
    listWorkspaceFiles: workspaceService.listWorkspaceFiles,
    readWorkspaceFile: workspaceService.readWorkspaceFile,
    saveWorkspaceFile: workspaceService.saveWorkspaceFile,
    uploadWorkspaceFile: workspaceService.uploadWorkspaceFile,
    createWorkspaceFile: workspaceService.createWorkspaceFile,
    createWorkspaceDirectory: workspaceService.createWorkspaceDirectory,
    createWorkspaceFileDownloadUrl: workspaceService.createWorkspaceFileDownloadUrl,
    getWorkspaceMcpConfig: workspaceService.getWorkspaceMcpConfig,
    saveWorkspaceMcpConfig: workspaceService.saveWorkspaceMcpConfig,
    listConnectedRepos: githubService.listConnectedRepos,
    createGithubConnectUrl: githubService.createGithubConnectUrl,
    getGithubConnection: githubService.getGithubConnection,
    disconnectGithub: githubService.disconnectGithub,
    listGoogleWorkspaceServices: googleWorkspaceService.listGoogleWorkspaceServices,
    listGoogleConnections: googleWorkspaceService.listGoogleConnections,
    getGoogleConnection: googleWorkspaceService.getGoogleConnection,
    deleteGoogleConnection: googleWorkspaceService.deleteGoogleConnection,
    startGoogleConnection: googleWorkspaceService.startGoogleConnection,
    getWorkspaceGoogleConnection: googleWorkspaceService.getWorkspaceGoogleConnection,
    bindWorkspaceGoogleConnection: googleWorkspaceService.bindWorkspaceGoogleConnection,
    unbindWorkspaceGoogleConnection: googleWorkspaceService.unbindWorkspaceGoogleConnection,
  });
}

module.exports = {createApiHandlers};
