"use strict";

function createApiHandlers({agentAuthService, environmentKeysService, openAiCodexAuthService, piPackagesService, workspaceAgentAssetsService, workspaceService, githubService, operations}) {
  return Object.freeze({
    ...operations,
    getPiAuth: agentAuthService.getPiAuth,
    savePiAuthProvider: agentAuthService.savePiAuthProvider,
    deletePiAuthProvider: agentAuthService.deletePiAuthProvider,
    deletePiAuthEntry: agentAuthService.deletePiAuthEntry,
    listGenericEnvironmentKeys: environmentKeysService.listGenericEnvironmentKeys,
    createGenericEnvironmentKey: environmentKeysService.createGenericEnvironmentKey,
    updateGenericEnvironmentKey: environmentKeysService.updateGenericEnvironmentKey,
    deleteGenericEnvironmentKey: environmentKeysService.deleteGenericEnvironmentKey,
    startOpenAiCodexDeviceCode: openAiCodexAuthService.startOpenAiCodexDeviceCode,
    completeOpenAiCodexDeviceCode: openAiCodexAuthService.completeOpenAiCodexDeviceCode,
    saveSessionPiAuthSelection: agentAuthService.saveSessionPiAuthSelection,
    listPiPackages: piPackagesService.listPiPackages,
    installPiPackage: piPackagesService.installPiPackage,
    removePiPackage: piPackagesService.removePiPackage,
    updatePiPackage: piPackagesService.updatePiPackage,
    listWorkspaceSkills: workspaceAgentAssetsService.listWorkspaceSkills,
    saveWorkspaceSkill: workspaceAgentAssetsService.saveWorkspaceSkill,
    deleteWorkspaceSkill: workspaceAgentAssetsService.deleteWorkspaceSkill,
    listPiSkills: workspaceAgentAssetsService.listPiSkills,
    savePiSkill: workspaceAgentAssetsService.savePiSkill,
    deletePiSkill: workspaceAgentAssetsService.deletePiSkill,
    listWorkspaceSubagents: workspaceAgentAssetsService.listWorkspaceSubagents,
    saveWorkspaceSubagent: workspaceAgentAssetsService.saveWorkspaceSubagent,
    deleteWorkspaceSubagent: workspaceAgentAssetsService.deleteWorkspaceSubagent,
    listWorkspaces: workspaceService.listWorkspaces,
    createWorkspace: workspaceService.createWorkspace,
    deleteWorkspace: workspaceService.deleteWorkspace,
    listWorkspaceFiles: workspaceService.listWorkspaceFiles,
    readWorkspaceFile: workspaceService.readWorkspaceFile,
    saveWorkspaceFile: workspaceService.saveWorkspaceFile,
    uploadWorkspaceFile: workspaceService.uploadWorkspaceFile,
    createWorkspaceFile: workspaceService.createWorkspaceFile,
    createWorkspaceDirectory: workspaceService.createWorkspaceDirectory,
    createWorkspaceFileDownloadUrl: workspaceService.createWorkspaceFileDownloadUrl,
    getWorkspaceMcpConfig: workspaceService.getWorkspaceMcpConfig,
    saveWorkspaceMcpConfig: workspaceService.saveWorkspaceMcpConfig,
    listConnectedRepos: githubService.listConnectedRepos,
    createGithubConnectUrl: githubService.createGithubConnectUrl,
    getGithubConnection: githubService.getGithubConnection,
    disconnectGithub: githubService.disconnectGithub,
  });
}

module.exports = {createApiHandlers};
