"use strict";

function createApiHandlers({piService, agentAuthService, environmentKeysService, workspaceService, githubService, operations}) {
  return Object.freeze({
    ...operations,
    getPiAuth: agentAuthService.getPiAuth,
    savePiAuthProvider: agentAuthService.savePiAuthProvider,
    deletePiAuthProvider: agentAuthService.deletePiAuthProvider,
    deletePiAuthEntry: agentAuthService.deletePiAuthEntry,
    listGenericEnvironmentKeys: environmentKeysService.listGenericEnvironmentKeys,
    createGenericEnvironmentKey: environmentKeysService.createGenericEnvironmentKey,
    updateGenericEnvironmentKey: environmentKeysService.updateGenericEnvironmentKey,
    deleteGenericEnvironmentKey: environmentKeysService.deleteGenericEnvironmentKey,
    startOpenAiCodexDeviceCode: piService.startOpenAiCodexDeviceCode,
    completeOpenAiCodexDeviceCode: piService.completeOpenAiCodexDeviceCode,
    saveSessionPiAuthSelection: agentAuthService.saveSessionPiAuthSelection,
    listPiPackages: piService.listPiPackages,
    installPiPackage: piService.installPiPackage,
    removePiPackage: piService.removePiPackage,
    updatePiPackage: piService.updatePiPackage,
    listWorkspaceSkills: piService.listWorkspaceSkills,
    saveWorkspaceSkill: piService.saveWorkspaceSkill,
    deleteWorkspaceSkill: piService.deleteWorkspaceSkill,
    listPiSkills: piService.listPiSkills,
    savePiSkill: piService.savePiSkill,
    deletePiSkill: piService.deletePiSkill,
    listWorkspaceSubagents: piService.listWorkspaceSubagents,
    saveWorkspaceSubagent: piService.saveWorkspaceSubagent,
    deleteWorkspaceSubagent: piService.deleteWorkspaceSubagent,
    listWorkspaces: workspaceService.listWorkspaces,
    createWorkspace: workspaceService.createWorkspace,
    deleteWorkspace: workspaceService.deleteWorkspace,
    listWorkspaceFiles: workspaceService.listWorkspaceFiles,
    readWorkspaceFile: workspaceService.readWorkspaceFile,
    saveWorkspaceFile: workspaceService.saveWorkspaceFile,
    uploadWorkspaceFile: workspaceService.uploadWorkspaceFile,
    createWorkspaceFile: workspaceService.createWorkspaceFile,
    createWorkspaceDirectory: workspaceService.createWorkspaceDirectory,
    createWorkspaceFileDownloadUrl: workspaceService.createWorkspaceFileDownloadUrl,
    getWorkspaceMcpConfig: workspaceService.getWorkspaceMcpConfig,
    saveWorkspaceMcpConfig: workspaceService.saveWorkspaceMcpConfig,
    listConnectedRepos: githubService.listConnectedRepos,
    createGithubConnectUrl: githubService.createGithubConnectUrl,
    getGithubConnection: githubService.getGithubConnection,
    disconnectGithub: githubService.disconnectGithub,
  });
}

module.exports = {createApiHandlers};
