"use strict";

const fs = require("fs/promises");
const path = require("path");

const CODEX_MCP_BEGIN = "# BEGIN MAPACHE MCP";
const CODEX_MCP_END = "# END MAPACHE MCP";

function parseMcpConfig(value) {
  try {
    const parsed = JSON.parse(String(value || "{}"));
    const servers = parsed && parsed.mcpServers && typeof parsed.mcpServers === "object" && !Array.isArray(parsed.mcpServers) ?
      parsed.mcpServers :
      {};
    return {mcpServers: servers};
  } catch (error) {
    console.error("invalid MCP_CONFIG, ignoring MCP servers", error);
    return {mcpServers: {}};
  }
}

function createMcpConfigService({config}) {
  const mcpConfig = parseMcpConfig(config.mcpConfigRaw);

  async function materializeMcpConfig(harness = null) {
    await writeJsonFile(path.join(config.workspaceDir, ".mcp.json"), mcpConfig);
    const harnessId = harness && harness.id ? harness.id : String(config.harnessId || config.terminalKind || "").trim().toLowerCase();
    if (harnessId === "codex") {
      const targetPath = config.codexConfigPath || path.join(config.workspaceDir, ".codex", "config.toml");
      await writeCodexConfig(targetPath, mcpConfig);
    }
    return {
      ok: true,
      harness: harnessId || "shell",
      serverCount: Object.keys(mcpConfig.mcpServers).length,
    };
  }

  return {materializeMcpConfig};
}

async function writeJsonFile(filePath, value) {
  await fs.mkdir(path.dirname(filePath), {recursive: true});
  await fs.writeFile(filePath, JSON.stringify(value, null, 2) + "\n", "utf8");
}

async function writeCodexConfig(filePath, mcpConfig) {
  await fs.mkdir(path.dirname(filePath), {recursive: true});
  const existing = await fs.readFile(filePath, "utf8").catch((error) => {
    if (error && error.code === "ENOENT") return "";
    throw error;
  });
  await fs.writeFile(filePath, mergeCodexMcpToml(existing, mcpConfig), "utf8");
}

function codexMcpToml(mcpConfig) {
  const lines = [CODEX_MCP_BEGIN, "# Generated by Mapache. Manage MCP servers from the right drawer."];
  for (const [name, server] of Object.entries(mcpConfig.mcpServers || {})) {
    if (!server || typeof server !== "object") continue;
    lines.push("", "[mcp_servers." + tomlKey(name) + "]");
    if (server.command) {
      lines.push("command = " + tomlString(server.command));
      if (Array.isArray(server.args) && server.args.length) {
        lines.push("args = [" + server.args.map(tomlString).join(", ") + "]");
      }
    }
    if (server.url) lines.push("url = " + tomlString(server.url));
    if (server.cwd) lines.push("cwd = " + tomlString(server.cwd));
    if (server.env && typeof server.env === "object" && Object.keys(server.env).length) {
      lines.push("env = { " + tomlInlineTable(server.env) + " }");
    }
    if (server.headers && typeof server.headers === "object" && Object.keys(server.headers).length) {
      lines.push("headers = { " + tomlInlineTable(server.headers) + " }");
    }
  }
  lines.push("", CODEX_MCP_END);
  return lines.join("\n") + "\n";
}

function mergeCodexMcpToml(existing, mcpConfig) {
  const generated = codexMcpToml(mcpConfig).trimEnd();
  const text = String(existing || "").trimEnd();
  const start = text.indexOf(CODEX_MCP_BEGIN);
  const end = text.indexOf(CODEX_MCP_END);
  if (start >= 0 && end > start) {
    return text.slice(0, start).trimEnd() + "\n\n" + generated + "\n" + text.slice(end + CODEX_MCP_END.length).trimStart();
  }
  return text ? text + "\n\n" + generated + "\n" : generated + "\n";
}

function tomlInlineTable(value) {
  return Object.entries(value).map(([key, item]) => tomlKey(key) + " = " + tomlString(item)).join(", ");
}

function tomlKey(value) {
  const key = String(value || "");
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

function tomlString(value) {
  return JSON.stringify(String(value || ""));
}

module.exports = {codexMcpToml, createMcpConfigService, mergeCodexMcpToml, parseMcpConfig};
