"use strict";

const fs = require("fs/promises");
const path = require("path");

const CODEX_MCP_BEGIN = "# BEGIN MAPACHE MCP";
const CODEX_MCP_END = "# END MAPACHE MCP";
const CHROME_DEVTOOLS_MCP_PACKAGE = "chrome-devtools-mcp@1.6.0";

function parseMcpConfig(value) {
  try {
    const parsed = JSON.parse(String(value || "{}"));
    const servers = parsed && parsed.mcpServers && typeof parsed.mcpServers === "object" && !Array.isArray(parsed.mcpServers) ?
      parsed.mcpServers :
      {};
    return {mcpServers: servers};
  } catch (error) {
    console.error("invalid MCP_CONFIG, ignoring MCP servers", error);
    return {mcpServers: {}};
  }
}

function createMcpConfigService({config}) {
  const mcpConfig = runnerMcpConfig(config);

  async function materializeMcpConfig(harness = null) {
    await writeJsonFile(path.join(config.workspaceDir, ".mcp.json"), piMcpConfig(mcpConfig));
    const harnessId = harness && harness.id ? harness.id : String(config.harnessId || config.terminalKind || "").trim().toLowerCase();
    if (harnessId === "codex") {
      const targetPath = config.codexConfigPath || path.join(config.workspaceDir, ".codex", "config.toml");
      await writeCodexConfig(targetPath, mcpConfig);
    }
    return {
      ok: true,
      harness: harnessId || "shell",
      serverCount: Object.keys(mcpConfig.mcpServers).length,
    };
  }

  return {materializeMcpConfig};
}

function runnerMcpConfig(config = {}) {
  const parsed = parseMcpConfig(config.mcpConfigRaw);
  if (!config.chromeEnabled && !config.runnerCapabilities?.chrome) return parsed;
  return {
    mcpServers: {
      ...parsed.mcpServers,
      "chrome-devtools": {
        command: "chrome-devtools-mcp",
        args: ["--browser-url", config.browserCdpUrl || "http://127.0.0.1:9222", "--no-usage-statistics"],
        env: {CHROME_DEVTOOLS_MCP_NO_UPDATE_CHECKS: "1"},
      },
    },
  };
}

function piMcpConfig(mcpConfig = {}) {
  return {
    mcpServers: Object.fromEntries(Object.entries(mcpConfig.mcpServers || {}).map(([name, server]) => [
      name,
      piMcpServer(server),
    ])),
  };
}

function piMcpServer(server = {}) {
  const result = {};
  for (const key of ["command", "args", "env", "url", "cwd", "headers", "lifecycle", "directTools"]) {
    if (server[key] != null) result[key] = server[key];
  }
  if (server.authMode === "oauth2") {
    result.auth = "oauth";
    result.oauth = {
      ...(server.oauthClientRef ? {clientId: server.oauthClientRef} : {}),
      ...(server.scopes?.length ? {scope: server.scopes.join(" ")} : {}),
      ...(server.oauthRedirectUri ? {redirectUri: server.oauthRedirectUri} : {}),
      ...(server.secretRefs?.clientSecret ? {clientSecret: `\${${server.secretRefs.clientSecret}}`} : {}),
    };
  } else if (server.authMode === "bearer_env") {
    result.auth = "bearer";
    if (server.bearerTokenEnv) result.bearerTokenEnv = server.bearerTokenEnv;
  }
  return result;
}

async function writeJsonFile(filePath, value) {
  await fs.mkdir(path.dirname(filePath), {recursive: true});
  await fs.writeFile(filePath, JSON.stringify(value, null, 2) + "\n", "utf8");
}

async function writeCodexConfig(filePath, mcpConfig) {
  await fs.mkdir(path.dirname(filePath), {recursive: true});
  const existing = await fs.readFile(filePath, "utf8").catch((error) => {
    if (error && error.code === "ENOENT") return "";
    throw error;
  });
  await fs.writeFile(filePath, mergeCodexMcpToml(existing, mcpConfig), "utf8");
}

function codexMcpToml(mcpConfig) {
  const lines = [CODEX_MCP_BEGIN, "# Generated by Mapache. Manage MCP servers from the right drawer."];
  for (const [name, server] of Object.entries(mcpConfig.mcpServers || {})) {
    if (!server || typeof server !== "object") continue;
    lines.push("", "[mcp_servers." + tomlKey(name) + "]");
    if (server.command) {
      lines.push("command = " + tomlString(server.command));
      if (Array.isArray(server.args) && server.args.length) {
        lines.push("args = [" + server.args.map(tomlString).join(", ") + "]");
      }
    }
    if (server.url) lines.push("url = " + tomlString(server.url));
    if (server.cwd) lines.push("cwd = " + tomlString(server.cwd));
    if (server.env && typeof server.env === "object" && Object.keys(server.env).length) {
      lines.push("env = { " + tomlInlineTable(server.env) + " }");
    }
    const {staticHeaders, envHeaders} = splitCodexHeaders(server);
    if (staticHeaders && Object.keys(staticHeaders).length) {
      lines.push("http_headers = { " + tomlInlineTable(staticHeaders) + " }");
    }
    if (envHeaders && Object.keys(envHeaders).length) {
      lines.push("env_http_headers = { " + tomlInlineTable(envHeaders) + " }");
    }
    if (server.bearerTokenEnv) lines.push("bearer_token_env_var = " + tomlString(server.bearerTokenEnv));
    if (Array.isArray(server.scopes) && server.scopes.length) {
      lines.push("scopes = [" + server.scopes.map(tomlString).join(", ") + "]");
    }
    if (server.oauthClientRef) {
      lines.push("oauth = { client_id = " + tomlString(server.oauthClientRef) + " }");
    }
  }
  lines.push("", CODEX_MCP_END);
  return lines.join("\n") + "\n";
}

function splitCodexHeaders(server = {}) {
  const staticHeaders = {};
  const envHeaders = {};
  for (const [name, value] of Object.entries(server.headers || {})) {
    const envReference = parseEnvReference(value);
    if (envReference) envHeaders[name] = envReference;
    else staticHeaders[name] = value;
  }
  for (const [secretName, envReference] of Object.entries(server.secretRefs || {})) {
    if (secretName === "accessToken") {
      envHeaders.Authorization = envReference;
    }
  }
  return {staticHeaders, envHeaders};
}

function parseEnvReference(value) {
  const text = String(value || "").trim();
  const match = text.match(/^\$\{([A-Z][A-Z0-9_]*)\}$|^\$env:([A-Z][A-Z0-9_]*)$/);
  return match ? (match[1] || match[2]) : "";
}

function mergeCodexMcpToml(existing, mcpConfig) {
  const generated = codexMcpToml(mcpConfig).trimEnd();
  const text = String(existing || "").trimEnd();
  const start = text.indexOf(CODEX_MCP_BEGIN);
  const end = text.indexOf(CODEX_MCP_END);
  if (start >= 0 && end > start) {
    return text.slice(0, start).trimEnd() + "\n\n" + generated + "\n" + text.slice(end + CODEX_MCP_END.length).trimStart();
  }
  return text ? text + "\n\n" + generated + "\n" : generated + "\n";
}

function tomlInlineTable(value) {
  return Object.entries(value).map(([key, item]) => tomlKey(key) + " = " + tomlString(item)).join(", ");
}

function tomlKey(value) {
  const key = String(value || "");
  return /^[A-Za-z0-9_-]+$/.test(key) ? key : tomlString(key);
}

function tomlString(value) {
  return JSON.stringify(String(value || ""));
}

module.exports = {
  CHROME_DEVTOOLS_MCP_PACKAGE,
  codexMcpToml,
  createMcpConfigService,
  mergeCodexMcpToml,
  parseMcpConfig,
  piMcpConfig,
  piMcpServer,
  runnerMcpConfig,
};
