export const OPERATION_KEYS = Object.freeze({
  APP_REFRESH: "app.refresh",
  GIT_COMMIT: "git.commit",
  GIT_PULL: "git.pull",
  GIT_PUSH: "git.push",
  GIT_PULL_REQUEST: "git.pull-request",
  GIT_STAGE: "git.stage",
  GIT_UNSTAGE: "git.unstage",
  SESSION_CREATE: "session.create",
  SESSION_DELETE: "session.delete",
  SESSION_RESIZE: "session.resize",
  SESSION_RESTART: "session.restart",
  SESSION_STOP: "session.stop",
  SSH_FORWARD_CLOSE: "ssh.forward-close",
  SSH_FORWARD_CREATE: "ssh.forward-create",
  WORKSPACE_CREATE: "workspace.create",
  WORKSPACE_DELETE: "workspace.delete",
  WORKSPACE_FILES_REFRESH: "workspace-files.refresh",
  WORKSPACE_SELECT: "workspace.select",
});
