export const OPERATION_KEYS = Object.freeze({
  APP_REFRESH: "app.refresh",
  SESSION_CREATE: "session.create",
  SESSION_DELETE: "session.delete",
  SESSION_EDIT: "session.edit",
  SESSION_RESIZE: "session.resize",
  SESSION_RETRY: "session.retry",
  SESSION_RESTART: "session.restart",
  SESSION_STOP: "session.stop",
  WORKSPACE_CREATE: "workspace.create",
  WORKSPACE_DELETE: "workspace.delete",
  WORKSPACE_TOGGLE: "workspace.toggle",
  WORKSPACE_RENAME: "workspace.rename",
  WORKSPACE_SELECT: "workspace.select",
});
